site_name: GoElastic client for Elasticsearch
site_url: https://github.com/grokify/goelastic
repo_url: https://github.com/grokify/goelastic.git
docs_dir: docs
theme: readthedocs
pages:
# Introduction:
- ['README.md', 'Introduction', 'Elastirad']
